### ISSUE TITLE
Add pagination to Sermon Series listing

### ISSUE THREAD

**Issue by isaacjwilliams** [wfth/wo#17]
Now that I've updated the ACL on the sermon series images to public read and they're showing up in the index, it takes ~2 seconds to load the entire page, even on localhost. Before, it was instantaneous. This means we'll probably have to paginate after all.

**Comment by aiwilliams** [comment]
I think this is a function of the browser working to load the images. There may be things we can do to speed it up, such as specify the size attributes on the `img` html tag. I would avoid the pagination work until we look into that 👍

**Comment by aiwilliams** [comment]
Let's leave this one alone for now. It loads really, really fast for me and once the images are cached it will load fast for everyone 😄
