### ISSUE TITLE
Retain order from wisdomonline.org (?)

### ISSUE THREAD

**Issue by isaacjwilliams** [wfth/wo#18]
When Converter seeds the database from Collector, it retains the original order. However, on an update, the updated record is rendered at the bottom of the list.

I wonder if this really matters to Mr. Scott (hence the question mark).

**Comment by aiwilliams** [comment]
What column currently controls the sorting? Can we simply avoid updating that column value when we edit existing sermons? I suppose we'll need to understand how to order in the long run because adding new sermons will mean no order for those new ones 🤔

**Comment by isaacjwilliams** [comment]
@aiwilliams They seem to be naturally ordered by the `updated_at` field. Other than the field that the user actually means to update (E.G. price), it's the only thing changing, and `select * from sermons where id = 1` returns this:

```
 id |         updated_at         
----+----------------------------
  2 | 2017-06-29 17:35:28
  3 | 2017-06-29 17:35:28
  4 | 2017-06-29 17:35:28
  5 | 2017-06-29 17:35:28
  6 | 2017-06-29 17:35:28
  7 | 2017-06-29 17:35:28
  8 | 2017-06-29 17:35:28
  9 | 2017-06-29 17:35:28
  1 | 2017-06-29 17:39:01.942841
(9 rows)
```

I'm maintaining order when I convert from Collector to WO by making sure all of my queries include `order by id`. We could do the same thing in WO, but that seems kind of lame (like we discussed before). Do you want an order field on WO records? I used something similar for tickets in the Desoto Caverns app. Actually, you can go see exactly what I did there if you want. It's open source after all! :smile:

**Comment by aiwilliams** [comment]
I think that what we have is fine for now. Let's ask the customer how they want to order it and we'll create an Issue when the time comes.
