### ISSUE TITLE
Allow visitor to add an item to a cart

### ISSUE THREAD

**Issue by aiwilliams** [wfth/wo#26]
MVP! The primary goal is to work out:

- [ ] place an add to cart button in the right places
- [ ] create a database structure to represent the cart
- [ ] associate the cart with the current http session

**Comment by isaacjwilliams** [comment]
It would appear that our only real option for a "cake mix" is [NectarCommerce](https://github.com/vinsol/nectarcommerce), and it seems quite young. I recommend clicking around [the NectarCommerce sample app](http://nectarcommerce.vinsol.com/) so you can see what we'd get without customization.

Other than that, I think we're stuck with raw ingredients and grunt work. 😕

**Comment by aiwilliams** [comment]
We're going to build one thing at a time. Closing this in favor of more specific Issues.
