### ISSUE TITLE
Allow download of transcript PDF

### ISSUE THREAD

**Issue by aiwilliams** [wfth/wo#28]

**Comment by aiwilliams** [comment]
Use S3 gem to move transcript files so they do not have URL encoding in the name: `name%20of%20file.pdf` should be `name of file.pdf`. You may want to look at S3 docs to be sure of how names with spaces are supposed to be handled.

**Comment by isaacjwilliams** [comment]
Closed by https://github.com/wfth/collector/commit/c2b7fe033749d99c61042e4a025eda5f1c51d3bc, https://github.com/wfth/converter/commit/4cacd3d8a20bd1d3e35ce6697a5f7ae841b6ffda, and https://github.com/wfth/wo/commit/0515cb3364e6c4d5b89ca4cf2abeb6b758f5e9ea.
