### ISSUE TITLE
Associate cart with user at the right times

### ISSUE THREAD

**Issue by aiwilliams** [wfth/wo#36]
When there is a cart in the session but I'm not logged in:

- [ ] Associate cart to user on login
- [ ] Merge cart with existing cart on login

When there is a cart in the session and I'm logged in:

- [ ] Remove cart from session on logout

**Comment by isaacjwilliams** [comment]
See e9996951bccde2155d8aee8d4733efb609cea4b1, 53be83743c069574945509efa30ce19bf3ce8d9b, and 0d4e936bb35434d71e5eacdb1e5cd4ca95bf1c93.
