### ISSUE TITLE
Attach images to sermon series using Javascript and AWS

### ISSUE THREAD

**Issue by isaacjwilliams** [wfth/wo#7]

**Comment by isaacjwilliams** [comment]
I've been looking into this and I can't find any AWS SDKs except for [ex_aws](https://github.com/CargoSense/ex_aws/), which doesn't seem to have anything like `get_session_token` (or any STS-related functions at all).

**Comment by aiwilliams** [comment]
I'd stay away from that for now. Look into Elixir's standard or recommended URL/HTTP libraries. I think it fine to construct your own HTTP request to STS service.

**Comment by aiwilliams** [comment]
We've reviewed Elixir AWS library options more carefully and decided to avoid STS for now. An upload/download user account will be used.

**Comment by isaacjwilliams** [comment]
See a259d6131373bd643c61518486292efe1f42d834, 440deca916eb386368305fa625ae70e426aee46c, and acb6361b5e3e8a211ba82a9cf114681b57328170.
